language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer global require "phpunit/phpunit=4.8.6"

script:
  - phpunit
